openapi: 3.0.0
info:
  title: Final Project
  version: 1.0.0
  description: |
    **Final Project**  
tags:
  - name: Login & Register
    description: ------
  - name: Products
    description: ------
  - name: Users
    description: ------

servers:
  - url: http://localhost:8000
  - url: https://secondhand-2-binar-final.herokuapp.com

components:
  schemas:
    Login:
      type: object
      properties:
        # id:
        #   type: number
        #   example: 1
        # name:
        #   type: string
        #   example: name
        # city:
        #   type: string
        #   example: city
        # address:
        #   type: string
        #   example: city 
        # phone:
        #   type: string
        #   example: 085754210823 
        token:
          type: string
          example: 2log16x25A
    LoginData:
      type: object
      properties:
        email:
          type: string
          example: name@gmail.com
        password:
          type: string
          example: 12345
    RegisterData:
      type: object
      properties:
        name:
          type: string
          example: name
        email:
          type: string
          example: name@gmail.com
        password:
          type: string
          example: 12345
    ProfilData:
      type: object
      properties:
        name:
          type: string
          example: name
        email:
          type: string
          example: name@gmail.com
        password:
          type: string
          example: 12345
        city:
          type: string
          example: city
        address:
          type: string
          example: city 
        phone:
          type: string
          example: 085754210823 
    ProfilDataRes:
      type: object
      properties:
        name:
          type: string
          example: name
        email:
          type: string
          example: name@gmail.com
        password:
          type: string
          example: 12345
        city:
          type: string
          example: city
        address:
          type: string
          example: city 
        phone:
          type: string
          example: 085754210823 
        image:
          type: string
          example: users-image_1
    CurrentUser:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: name
        city:
          type: string
          example: city
        address:
          type: string
          example: city 
        phone:
          type: string
          example: 085754210823
        image:
          type: string
          example: users-image_1
    Products:
      type: object
      properties:
        user_id:
          type: number
          example: 1
        category_id:
          type: number
          example: 1
        name:
          type: string
          example: productName
        price:
          type: number
          format: float
          example: 100000.2
        description:
          type: string
          example: productDescription
        # images:
        #   type: array
        #   items:
        #     type: string
        #   example: 
        #     [
        #     "Images_product_1-1",
        #     "Images_product_1-2",
        #     "Images_product_1-3",
        #     "Images_product_1-4"
        #     ]
    ProductsId:
      type: object
      properties:
        id:
          type: number
          example: 1
        user_id:
          type: number
          example: 1
        category_id:
          type: number
          example: 1
        name:
          type: string
          example: productName
        price:
          type: number
          format: float
          example: 100000.1
        description:
          type: string
          example: productDescription
        sold:
          type: boolean
          example: false
        images:
          type: array
          items:
            type: string
          example: 
            [
            "Images_product_1-1",
            "Images_product_1-2",
            "Images_product_1-3",
            "Images_product_1-4"
            ]
        created_at:
          type: number
          format: datetime
          example: 1970-01-01 00:00:01
        updated_at:
          type: number
          format: datetime
          example: 1970-01-01 00:00:01
  requestBodies:
    LoginRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/LoginData"
    RegisterRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RegisterData"
    ProfilRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProfilData"
    ProductsRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Products"
    ProductsRequestId:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductsId"
    ProductsRequestputId:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductsId"
  responses:
    LoginResponse:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Login"
    ProfilResponse:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProfilDataRes"
    CurrentUserResponse:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CurrentUser"
    ProductResponse:
      description: PostProducts
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Products"
    ProductsResponse:
      description: List All Products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Products"
            example:
              DefaultSample: 
              value:
                - id: 1
                  user_id: 1
                  category_id: 1
                  name: productName1
                  price: 100000.1
                  description: productDescription1
                  sold: false
                  image: [
                    "Images_product_1-1",
                    "Images_product_1-2",
                    "Images_product_1-3",
                    "Images_product_1-4"
                    ]
                  created_at: 1970-01-01 00:00:01
                  update_at: 1970-01-01 00:00:01
                - id: 2
                  user_id: 2
                  category_id: 2
                  name: productName2
                  price: 100000.2
                  description: productDescription2
                  sold: false
                  image: [
                    "Images_product_2-1",
                    "Images_product_2-2",
                    "Images_product_2-3",
                    "Images_product_2-4"
                    ]
                  created_at: 1970-02-02 00:00:02
                  update_at: 1970-02-02 00:00:02
                - id: 3
                  user_id: 3
                  category_id: 3
                  name: productName3
                  price: 100000.3
                  description: productDescription3
                  sold: false
                  image: [
                    "Images_product_3-1",
                    "Images_product_3-2",
                    "Images_product_3-3",
                    "Images_product_3-4"
                    ]
                  created_at: 1970-03-03 00:00:03
                  updated_at: 1970-03-03 00:00:03
    ProductsByIdResponses:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductsId"
    PutProductsByIDResponses:
      description: updated
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductsId"
  
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer

paths:
  /api/v1/login:
    post:
      tags:
        - Login & Register
      summary: Login
      description: Login endpoint
      requestBody:
        $ref: "#/components/requestBodies/LoginRequest"
      responses:
        200:
          $ref: "#/components/responses/LoginResponse"

  /api/v1/register:
    post:
      tags:
        - Login & Register
      summary: Register
      description: Register endpoint
      requestBody:
        $ref: "#/components/requestBodies/RegisterRequest"
      responses:
        200:
          description: Success

  /api/v1/profil:
    put:
      tags:
        - Users
      summary: Put Profil Users endpoint
      description: Put Profil Users endpoint
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/ProfilRequest"
      responses:
        200:
          $ref: "#/components/responses/ProfilResponse"
          
  /api/v1/currentuser:
    get:
      tags:
        - Users
      summary: Get Current User
      description: Get Current User
      security:
        - bearerAuth: []
      responses:
        200:
          $ref: '#/components/responses/CurrentUserResponse'
  
  /api/v1/usersimageupload:
    post:
      tags:
        - Users
      summary: Uploads image's user
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: succes

  /api/v1/products/sale:
    get:
      tags:
        - Users
      summary: Get Products sale by user
      description: Get Products sale by user
      security:
        - bearerAuth: []
      responses:
        200:
          $ref: "#/components/responses/ProductsByIdResponses"
          
  /api/v1/products/sold:
    get:
      tags:
        - Users
      summary: Get Products sold by user
      description: Get Products sold by user
      security:
        - bearerAuth: []
      responses:
        200:
          description: success
    
  /api/v1/products:
    post:
      tags:
        - Products
      summary: Post Products
      description: Post Products endpoint
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/ProductsRequest"
      responses:
        200:
          $ref: "#/components/responses/ProductsByIdResponses"
    get:
      tags:
        - Products
      summary: Get Products
      description: Get Products endpoint
      responses:
        200:
          $ref: "#/components/responses/ProductsResponse"

  /api/v1/products/{id}:
    get:
      tags:
        - Products
      summary: Get Products by id
      description: Get Products by id endpoint
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        200:
          $ref: "#/components/responses/ProductsByIdResponses"

    put:
      tags:
        - Products
      summary: Put Products by id
      description: Put Products by id endpoint
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/ProductsRequest"
      responses:
        200:
          $ref: "#/components/responses/PutProductsByIDResponses"

    delete:
      tags:
        - Products
      summary: Delete Products by id
      description: Delete Products by id endpoint
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: delete
          
  /api/v1/productsimageupload:
    post:
      tags:
        - Products
      summary: Uploads image's products
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: succes

  